[CHK-1747] feat: add performance tests
pagopa/pagopa-aca-tests pull request #3
Opened 2023-07-24 13:16 UTC by MarcoAGreco

- Add performance tests

1) Create new debt position
2) Update existing debt position
3) Close existing debt position

2023-07-24 14:18 UTC, Fernando-Granato commented on src/performance/perf-update.test.ts
> +        { "Response status from POST newDebtPosition was 201": (r) => r.status == 200 },
```suggestion
        { "Response status from POST newDebtPosition was 200": (r) => r.status == 200 },
```

2023-07-24 14:20 UTC, Fernando-Granato commented on src/performance/perf-creation.test.ts
> +        { "Response status from POST newDebtPosition was 201": (r) => r.status == 201 },
```suggestion
        { "Response status from POST newDebtPosition was 200": (r) => r.status == 201 },
```

2023-07-24 14:20 UTC, Fernando-Granato commented on src/performance/perf-creation.test.ts
> +        paFiscalCode: "string",
Set example body not string constant

2023-07-24 14:20 UTC, Fernando-Granato commented on src/performance/perf-update.test.ts
> +        paFiscalCode: "string",
Set example body not string constant

2023-07-24 14:23 UTC, giovanniberti approved these changes

2023-07-24 14:24 UTC, giovanniberti requested changes
See comments by @Fernando-Granato

2023-07-24 14:24 UTC, Fernando-Granato commented on src/performance/perf-closure.test.ts
> +            executor: "constant-arrival-rate",
Instead of running an executor  **constant-arrival-rate** why don't we use an executor **ramping-vus**

2023-07-24 14:24 UTC, Fernando-Granato commented on src/performance/perf-creation.test.ts
> +            executor: "constant-arrival-rate",
Instead of running an executor  **constant-arrival-rate** why don't we use an executor **ramping-vus**

2023-07-24 14:24 UTC, Fernando-Granato commented on src/performance/perf-update.test.ts
> +            executor: "constant-arrival-rate",
Instead of running an executor  **constant-arrival-rate** why don't we use an executor **ramping-vus**

2023-07-25 07:48 UTC, Fernando-Granato commented on src/performance/perf-closure.test.ts
> +    createPositionBody.amount = 0;
You can configure it directly in the body

2023-07-25 07:48 UTC, Fernando-Granato commented on src/performance/perf-update.test.ts
> +    createPositionBody.amount = createPositionBody.amount + 100;
I don't think it's necessary

2023-07-25 07:55 UTC, Fernando-Granato commented on src/performance/perf-closure.test.ts
> +        "Content-Type": "application/json",
```suggestion
        "Content-Type": "application/json",
        'Ocp-Apim-Subscription-Key': config.API_SUBSCRIPTION_KEY,
```

2023-07-25 07:55 UTC, Fernando-Granato commented on src/performance/perf-creation.test.ts
> +        "Content-Type": "application/json",
```suggestion
         "Content-Type": "application/json",
        'Ocp-Apim-Subscription-Key': config.API_SUBSCRIPTION_KEY,
```

2023-07-25 07:55 UTC, Fernando-Granato commented on src/performance/perf-update.test.ts
> +        "Content-Type": "application/json",
```suggestion
         "Content-Type": "application/json",
        'Ocp-Apim-Subscription-Key': config.API_SUBSCRIPTION_KEY,
```

2023-07-25 15:18 UTC, giovanniberti approved these changes

2023-07-25 15:19 UTC, merged